---
- name: include pre_requisite_non_container.yml
  include: pre_requisite_non_container.yml
  when:
    - not containerized_deployment

- name: include pre_requisite_container.yml
  include: pre_requisite_container.yml
  when:
    - containerized_deployment

- name: include create_rgw_keyring.yml
  include: create_rgw_keyring.yml
  when:
    - not containerized_deployment

- name: include create_rgw_nfs_user.yml
  include: create_rgw_nfs_user.yml

- name: include start_nfs.yml
  include: start_nfs.yml
